// Generated by CoffeeScript 1.7.1
(function() {
  this.safeStringify = function(obj) {
    return JSON.stringify(obj).replace(/<\/script/g, '<\\/script').replace(/<!--/g, '<\\!--');
  };

  this.slugify = function(string) {
    string = string || "";
    string = string.toLowerCase();
    return string.replace(/[\s-]+/g, "-").replace(/[^\w-]*/g, "");
  };

  this.getRootComponent = function(component) {
    while (component._owner) {
      component = component._owner;
    }
    return component;
  };

  this.snapshotToArray = function(snapshot) {
    var elements;
    elements = [];
    snapshot.forEach(function(snap) {
      var element;
      element = snap.val();
      element.id = snap.name();
      elements.push(element);
      return false;
    });
    return elements;
  };

}).call(this);
